### ISSUE TITLE
Using Symfony GenericEvent

### ISSUE THREAD

**Issue by JustBlackBird** [KnpLabs/rad-domain-event#7]
The bundle contains a custom [even class](https://github.com/KnpLabs/rad-domain-event/blob/master/src/Knp/Rad/DomainEvent/Event.php) which is not actually a full-featured (missed [`__isset`](http://php.net/manual/en/language.oop5.overloading.php#object.isset) implementation and so on).

My question is why Symfony's [`GenericEvent`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/EventDispatcher/GenericEvent.php) was not used instead (or at least as a parent class)? It provide more functionality right out of the box.

If the maintainer is interested in such change I could provide a PR to use `GenericEvent` as a base class for `Knp\Rad\DomainEvent\Event`

**Comment by einenlum** [comment]
I guess the Event class we need is really simple, so if we can avoid a new dependency, let's do it.
If a maintainer is interested in using the Symfony event-dispatcher component as a dependency, feel free to reopen this issue :).
